### PR TITLE
Update for bevy's renamed camera bindings

### PR DESCRIPTION
**Pull request by rparrett**
Looks like bevy's not quite done breaking things.

https://github.com/bevyengine/bevy/commit/dd4a19632928556b88ffd53a9f8c3f615fce0095

### CODE REVIEW

**Comment by dmtaub** [comment]
Do we think this is stable now, or should we wait to see it settle down?

**Comment by rparrett** [comment]
I’m totally cool with letting things settle. I think that this: https://github.com/bevyengine/bevy/issues/1562 may break us again.

**Comment by dmtaub** [comment]
Hey so I was trying to use this and it appears that scaling is no longer working. Further, objects aren't showing up, and multiple tilemaps aren't rending in the correct order. See iso_main or ortho_main examples

**Comment by dmtaub** [comment]
Merged in with #46

**Pull request closed without merging**
